// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE66Pvzm2o-lMD7tDM1rL84OaDdj4k3Uk',
    appId: '1:446593118842:web:2d1995abdbe6a7361041c3',
    messagingSenderId: '446593118842',
    projectId: 'marchand-6bc55',
    authDomain: 'marchand-6bc55.firebaseapp.com',
    databaseURL: 'https://marchand-6bc55-default-rtdb.firebaseio.com',
    storageBucket: 'marchand-6bc55.firebasestorage.app',
    measurementId: 'G-12PMJGD4KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANpm8x1GYgefXU2ZKE5Viq3JcPj-ksSXQ',
    appId: '1:446593118842:android:68a02a696d17579a1041c3',
    messagingSenderId: '446593118842',
    projectId: 'marchand-6bc55',
    databaseURL: 'https://marchand-6bc55-default-rtdb.firebaseio.com',
    storageBucket: 'marchand-6bc55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV2yKbbPJyalAZOm7SpmLBZ2-8WqNdX-4',
    appId: '1:446593118842:ios:49afae29dc2ec7cb1041c3',
    messagingSenderId: '446593118842',
    projectId: 'marchand-6bc55',
    databaseURL: 'https://marchand-6bc55-default-rtdb.firebaseio.com',
    storageBucket: 'marchand-6bc55.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV2yKbbPJyalAZOm7SpmLBZ2-8WqNdX-4',
    appId: '1:446593118842:ios:49afae29dc2ec7cb1041c3',
    messagingSenderId: '446593118842',
    projectId: 'marchand-6bc55',
    databaseURL: 'https://marchand-6bc55-default-rtdb.firebaseio.com',
    storageBucket: 'marchand-6bc55.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE66Pvzm2o-lMD7tDM1rL84OaDdj4k3Uk',
    appId: '1:446593118842:web:28e34f34db3d1a0f1041c3',
    messagingSenderId: '446593118842',
    projectId: 'marchand-6bc55',
    authDomain: 'marchand-6bc55.firebaseapp.com',
    databaseURL: 'https://marchand-6bc55-default-rtdb.firebaseio.com',
    storageBucket: 'marchand-6bc55.firebasestorage.app',
    measurementId: 'G-XVCY6W1489',
  );
}
