// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd2NvW_5i8FTPHIpuqLEky1qwf8VETjZM',
    appId: '1:1047760327952:web:e205f1c4be15e4d5b24195',
    messagingSenderId: '1047760327952',
    projectId: 'notificationmypproject',
    authDomain: 'notificationmypproject.firebaseapp.com',
    storageBucket: 'notificationmypproject.firebasestorage.app',
    measurementId: 'G-THNM4DFYYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa7su-XlToaQ5ytR20hDgeSiXV0KdUq0U',
    appId: '1:1047760327952:android:061a2c4480e10dd4b24195',
    messagingSenderId: '1047760327952',
    projectId: 'notificationmypproject',
    storageBucket: 'notificationmypproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXYeiTarSDvpxPzYHOmoh7NYyeBai326c',
    appId: '1:1047760327952:ios:db05c135a8efaad3b24195',
    messagingSenderId: '1047760327952',
    projectId: 'notificationmypproject',
    storageBucket: 'notificationmypproject.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXYeiTarSDvpxPzYHOmoh7NYyeBai326c',
    appId: '1:1047760327952:ios:db05c135a8efaad3b24195',
    messagingSenderId: '1047760327952',
    projectId: 'notificationmypproject',
    storageBucket: 'notificationmypproject.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd2NvW_5i8FTPHIpuqLEky1qwf8VETjZM',
    appId: '1:1047760327952:web:0909299f5b7c6475b24195',
    messagingSenderId: '1047760327952',
    projectId: 'notificationmypproject',
    authDomain: 'notificationmypproject.firebaseapp.com',
    storageBucket: 'notificationmypproject.firebasestorage.app',
    measurementId: 'G-HHC580MG1C',
  );
}
